name: Workflow Action Test Pipeline

on:
  push:
    branches:
      - main
env:
  KAGGLE_USERNAME: $KAGGLE_USERNAME
  KAGGLE_KEY: $KAGGLE_KEY

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      # Install python!
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9

      # execute test pipeline
      - name: Continuous Integration
        run: |
          chmod +x ./main/project/tests.sh && cd ./main/project && ./tests.sh
